name: Auto Comment
on:
  pull_request:
    paths:
      - tests/*
jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_REPO: ${{ github.repository }}
          COMMENT: "⚠️  @${{ github.event.pull_request.user.login }}, your pull request contains changes to test files."
        run: 
          gh pr review $PR_NUMBER -r -b $COMMENT
